### ISSUE TITLE
Non-logged in users should use default visibility settings

### ISSUE THREAD

**Issue by vaniver** [tricycle/lesswrong#555] opened 2016-02-10 19:03 UTC
As discussed in lesswrong.com/r/discussion/lw/n9b/upcoming_lw_changes/d3qc , a user who is not logged in should not see heavily downvoted posts or links in the posts view, and heavily downvoted comments should be collapsed by default.

**Comment by xrpd** [comment] 2016-02-15 18:41
There is an ".ini" file global setting (hide_comment_threshold) that currently overrides a user's   hide comment preference (pref_min_comment_score). For example, if the global setting is "-4", but   the user's preference is "-5", the comment will be hidden/collapsed if the comment score is -4 or   less (I have confirmed this behavior in testing). It seems me that the user's preference should be   the governing score, but let me know your thoughts.

The global setting also applies to anonymous readers - e.g., comments with score -4 are   hidden/collapsed for anonymous readers. There is no equivalent global setting for links/posts, so   they appear regardless of score.

My thought was to introduce two new global parameters (default_min_link_score,   default_min_comment_score) and use these as the default parameters for users (the defaults for   pref_min_link_score and pref_min_comment_score are currently both hard coded at -2), and as the   working parameters for anonymous readers.

This provides a consistent experience, but seems to obviate the need for the currently existing   "hide_comment_threshold" setting. Is it okay to delete the "hide_comment_threshold" setting, or   should this remain as an independent setting that overrides user preferences?

**Comment by xrpd** [comment] 2016-02-16 19:43
Patch 559 is intended to resolve this issue.  I implemented as discussed in my previous comment.  I didn't delete 'hide_comment_threshold', but its value will no longer have an effect on system functionality.

**Comment by cdaloisio** [comment] 2016-02-18 23:53
Merged #559

**Closed by cdaloisio** 2016-02-18 23:53 UTC
